wallpaper_image = Image("holebg.png");
screen_width = Window.GetWidth();
screen_height = Window.GetHeight();
resized_wallpaper_image = wallpaper_image.Scale(screen_width,screen_height);
wallpaper_sprite = Sprite(resized_wallpaper_image);
wallpaper_sprite.SetZ(-100);

title_image = Image("title.png");
resized_title_image = title_image.Scale(screen_width,screen_height);
title_sprite = Sprite(resized_wallpaper_image);
title_sprite.SetZ(-99);
